### ISSUE TITLE
v1.0 or v1.2024

### ISSUE THREAD

**Issue by SamySam0** [BCHSI/philter-deidstable1_mirror#3]
In the repository under the tag v1.2024, you recommend using the v1.0 version of Philter. 
Is this still what you would recommend, or is v1.2024 a better and updated version of Philter?
Additionally, unlike the v1.0, v1.2024 does not produce a .xml with the detected PHI, instead, it directly masks entities inline with asterisks. Is there a way to obtain the xml file with all detected PHI?

**Comment by RedChrists** [comment]
The latest release is tagged as [v1.2024.1](https://github.com/BCHSI/philter-deidstable1_mirror/releases/tag/v1.2024.1). Please use this one.
Regarding your second question, please share your command here, so that I can reproduce the issue. Thanks!

**Comment by SamySam0** [comment]
> The latest release is tagged as [v1.2024.1](https://github.com/BCHSI/philter-deidstable1_mirror/releases/tag/v1.2024.1). Please use this one. Regarding your second question, please share your command here, so that I can reproduce the issue. Thanks!

Thank you! I will use the v.1.2024.1 from now on.
I've attached the tiny piece of code (notebook) I use to run Philter. After running, my results folder contains an inline de-identified letter (.txt) for each input letter, and a log folder. Can I assume log/phi_marked.json to be the output providing all detected PHI?

```python
import os

!git clone https://github.com/BCHSI/philter-deidstable1_mirror.git ./philter/src
%cd ./philter/src
!git checkout v1.2024.1
!pip install -r requirements.txt
%cd ../..

import nltk
nltk.download('averaged_perceptron_tagger')

os.mkdir('./philter/results')

%cd philter/src
!python3 deidpipe.py -i data/i2b2_notes/ -o ../results/ -f configs/philter_one2024.json 
%cd ../..
```

**Comment by RedChrists** [comment]
Since you seem to not be using any metadata, I recommend to add option "-d False". Otherwise, your output files might not be written.
And, yes log/phi_marked.json contains all tokens that were detected explicitly as PHI via a rule. There are additional redactions that occur in the output text as a fall-back for tokens that did not match any rule.
